//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_LIBRO_RECETA_PSICOTROPICO
    {
        public ALP_LIBRO_RECETA_PSICOTROPICO()
        {
            this.ALP_LIBRO_RECETA_PSICOTROPICO_INSUMO = new HashSet<ALP_LIBRO_RECETA_PSICOTROPICO_INSUMO>();
        }
    
        public string cod_libro_receta_psicotropico { get; set; }
        public string num_constancia_preparado { get; set; }
        public int cod_quimico_laboratorista { get; set; }
        public string nom_medico { get; set; }
        public Nullable<int> num_colegiatura_medico { get; set; }
        public string nom_paciente { get; set; }
        public string num_docu_paciente { get; set; }
        public System.DateTime fec_preparado { get; set; }
        public System.DateTime fec_vencimiento { get; set; }
        public int cod_usu_regi { get; set; }
        public System.DateTime fec_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ALP_CONSTANCIA_PREPARADO ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual ICollection<ALP_LIBRO_RECETA_PSICOTROPICO_INSUMO> ALP_LIBRO_RECETA_PSICOTROPICO_INSUMO { get; set; }
        public virtual RRH_Empleado RRH_Empleado { get; set; }
    }
}
