//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_HOJA_MERMA_INSUMO
    {
        public string num_hoja_merma { get; set; }
        public string cod_insumo { get; set; }
        public int cant_insumo { get; set; }
        public string motivo { get; set; }
        public int cant_constancia { get; set; }
        public int cant_diferencia { get; set; }
    
        public virtual ALP_HOJA_MERMA ALP_HOJA_MERMA { get; set; }
        public virtual ALP_INSUMO ALP_INSUMO { get; set; }
    }
}
