//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_RECETA
    {
        public ALP_RECETA()
        {
            this.ALP_ORDEN_PREPARADO = new HashSet<ALP_ORDEN_PREPARADO>();
        }
    
        public string cod_receta { get; set; }
        public string nom_preparado { get; set; }
        public string desc_receta { get; set; }
        public string nom_medico { get; set; }
        public int num_colegiatura_medico { get; set; }
        public string nom_paciente { get; set; }
        public string num_docu_paciente { get; set; }
        public string motivo { get; set; }
        public System.DateTime fec_emision { get; set; }
        public string estado { get; set; }
        public int cod_usu_regi { get; set; }
        public System.DateTime fec_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ICollection<ALP_ORDEN_PREPARADO> ALP_ORDEN_PREPARADO { get; set; }
    }
}
