//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_ORDEN_PREPARADO
    {
        public ALP_ORDEN_PREPARADO()
        {
            this.ALP_CONSTANCIA_PREPARADO = new HashSet<ALP_CONSTANCIA_PREPARADO>();
            this.ALP_ORDEN_PREPARADO_INSUMO = new HashSet<ALP_ORDEN_PREPARADO_INSUMO>();
        }
    
        public int num_orden_preparado { get; set; }
        public int cod_receta { get; set; }
        public int cod_sucursal { get; set; }
        public int cod_empleado { get; set; }
        public System.DateTime fec_orden { get; set; }
        public string observacion { get; set; }
        public string estado { get; set; }
        public int cod_usu_regi { get; set; }
        public System.DateTime fec_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ICollection<ALP_CONSTANCIA_PREPARADO> ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual RRH_Empleado RRH_Empleado { get; set; }
        public virtual ALP_RECETA ALP_RECETA { get; set; }
        public virtual RRH_Sucursal RRH_Sucursal { get; set; }
        public virtual ICollection<ALP_ORDEN_PREPARADO_INSUMO> ALP_ORDEN_PREPARADO_INSUMO { get; set; }
    }
}
