//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_INSUMO
    {
        public ALP_INSUMO()
        {
            this.ALP_CONSTANCIA_PREPARADO_INSUMO = new HashSet<ALP_CONSTANCIA_PREPARADO_INSUMO>();
            this.ALP_HOJA_MERMA_INSUMO = new HashSet<ALP_HOJA_MERMA_INSUMO>();
            this.ALP_ORDEN_PREPARADO_INSUMO = new HashSet<ALP_ORDEN_PREPARADO_INSUMO>();
        }
    
        public string cod_insumo { get; set; }
        public string nom_insumo { get; set; }
        public string unidad_medida { get; set; }
        public int concentracion { get; set; }
        public string estado { get; set; }
        public int cod_usu_regi { get; set; }
        public System.DateTime fec_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ICollection<ALP_CONSTANCIA_PREPARADO_INSUMO> ALP_CONSTANCIA_PREPARADO_INSUMO { get; set; }
        public virtual ICollection<ALP_HOJA_MERMA_INSUMO> ALP_HOJA_MERMA_INSUMO { get; set; }
        public virtual ICollection<ALP_ORDEN_PREPARADO_INSUMO> ALP_ORDEN_PREPARADO_INSUMO { get; set; }
    }
}
