//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_CONSTANCIA_PREPARADO_INSUMO
    {
        public string num_constancia_preparado { get; set; }
        public string cod_insumo { get; set; }
        public int cant_insumo_orden { get; set; }
        public int cant_insumo_constancia { get; set; }
        public int cant_insumo_diferencia { get; set; }
    
        public virtual ALP_CONSTANCIA_PREPARADO ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual ALP_INSUMO ALP_INSUMO { get; set; }
    }
}
