//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALP_SOLICITUD_TRANSPORTE
    {
        public string num_solicitud { get; set; }
        public string num_constancia_preparado { get; set; }
        public int cod_empleado { get; set; }
        public string observacion { get; set; }
        public System.DateTime fec_solicitud { get; set; }
        public int cod_usu_regi { get; set; }
        public System.DateTime fec_usu_regi { get; set; }
        public int cod_usu_modi { get; set; }
        public System.DateTime fec_usu_modi { get; set; }
    
        public virtual ALP_CONSTANCIA_PREPARADO ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual RRH_Empleado RRH_Empleado { get; set; }
    }
}
