//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDBoticasEntities : DbContext
    {
        public BDBoticasEntities()
            : base("name=BDBoticasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALP_CONSTANCIA_PREPARADO> ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual DbSet<ALP_CONSTANCIA_PREPARADO_INSUMO_ORDEN> ALP_CONSTANCIA_PREPARADO_INSUMO_ORDEN { get; set; }
        public virtual DbSet<ALP_HOJA_MERMA> ALP_HOJA_MERMA { get; set; }
        public virtual DbSet<ALP_HOJA_MERMA_INSUMO_CONSTANCIA> ALP_HOJA_MERMA_INSUMO_CONSTANCIA { get; set; }
        public virtual DbSet<ALP_INSUMO> ALP_INSUMO { get; set; }
        public virtual DbSet<ALP_LIBRO_RECETA> ALP_LIBRO_RECETA { get; set; }
        public virtual DbSet<ALP_LIBRO_RECETA_INSUMO> ALP_LIBRO_RECETA_INSUMO { get; set; }
        public virtual DbSet<ALP_LIBRO_RECETA_PSICOTROPICO> ALP_LIBRO_RECETA_PSICOTROPICO { get; set; }
        public virtual DbSet<ALP_LIBRO_RECETA_PSICOTROPICO_INSUMO> ALP_LIBRO_RECETA_PSICOTROPICO_INSUMO { get; set; }
        public virtual DbSet<ALP_ORDEN_PREPARADO> ALP_ORDEN_PREPARADO { get; set; }
        public virtual DbSet<ALP_ORDEN_PREPARADO_INSUMO> ALP_ORDEN_PREPARADO_INSUMO { get; set; }
        public virtual DbSet<ALP_RECETA> ALP_RECETA { get; set; }
        public virtual DbSet<ALP_SOLICITUD_TRANSPORTE> ALP_SOLICITUD_TRANSPORTE { get; set; }
        public virtual DbSet<RRH_EMPLEADO> RRH_EMPLEADO { get; set; }
        public virtual DbSet<RRH_Puesto> RRH_Puesto { get; set; }
        public virtual DbSet<RRH_SUCURSAL> RRH_SUCURSAL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
