//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDBoticasEntities : DbContext
    {
        public BDBoticasEntities()
            : base("name=BDBoticasEntities")
        {
            this.Configuration.LazyLoadingEnabled = true;
            this.Configuration.ProxyCreationEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALP_CONSTANCIA_PREPARADO> ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual DbSet<ALP_HOJA_MERMA> ALP_HOJA_MERMA { get; set; }
        public virtual DbSet<ALP_INSUMO> ALP_INSUMO { get; set; }
        public virtual DbSet<ALP_LIBRO_RECETA> ALP_LIBRO_RECETA { get; set; }
        public virtual DbSet<ALP_ORDEN_PREPARADO> ALP_ORDEN_PREPARADO { get; set; }
        public virtual DbSet<ALP_ORDEN_PREPARADO_INSUMO> ALP_ORDEN_PREPARADO_INSUMO { get; set; }
        public virtual DbSet<ALP_RECETA> ALP_RECETA { get; set; }
        public virtual DbSet<DIS_Control_Asignacion> DIS_Control_Asignacion { get; set; }
        public virtual DbSet<DIS_HojaRuta> DIS_HojaRuta { get; set; }
        public virtual DbSet<DIS_HojaRutaDetalle> DIS_HojaRutaDetalle { get; set; }
        public virtual DbSet<DIS_Pedido> DIS_Pedido { get; set; }
        public virtual DbSet<DIS_Pedido_Detalle> DIS_Pedido_Detalle { get; set; }
        public virtual DbSet<DIS_PresentacionProducto> DIS_PresentacionProducto { get; set; }
        public virtual DbSet<DIS_Producto> DIS_Producto { get; set; }
        public virtual DbSet<DIS_TipoProducto> DIS_TipoProducto { get; set; }
        public virtual DbSet<DIS_Transportista> DIS_Transportista { get; set; }
        public virtual DbSet<DIS_Vehiculo> DIS_Vehiculo { get; set; }
        public virtual DbSet<GCC_CLIENTE> GCC_CLIENTE { get; set; }
        public virtual DbSet<GCC_CLIENTE_JURIDICO> GCC_CLIENTE_JURIDICO { get; set; }
        public virtual DbSet<GCC_CLIENTE_NATURAL> GCC_CLIENTE_NATURAL { get; set; }
        public virtual DbSet<GCC_COMPROBANTE> GCC_COMPROBANTE { get; set; }
        public virtual DbSet<GCC_CONTRATO_CREDITO> GCC_CONTRATO_CREDITO { get; set; }
        public virtual DbSet<GCC_CUENTA_CLIENTE> GCC_CUENTA_CLIENTE { get; set; }
        public virtual DbSet<GCC_DOCUMENTO_RECHAZO> GCC_DOCUMENTO_RECHAZO { get; set; }
        public virtual DbSet<GCC_EMPLEADO_INF_CREDITICIO> GCC_EMPLEADO_INF_CREDITICIO { get; set; }
        public virtual DbSet<GCC_EMPLEADO_SOL_CREDITO> GCC_EMPLEADO_SOL_CREDITO { get; set; }
        public virtual DbSet<GCC_INFORME_CREDITICIO> GCC_INFORME_CREDITICIO { get; set; }
        public virtual DbSet<GCC_NOTIFICACION> GCC_NOTIFICACION { get; set; }
        public virtual DbSet<GCC_PLAN_CREDITO> GCC_PLAN_CREDITO { get; set; }
        public virtual DbSet<GCC_POLITICA_CREDITO> GCC_POLITICA_CREDITO { get; set; }
        public virtual DbSet<GCC_POLITICAS_NOTIFICACION> GCC_POLITICAS_NOTIFICACION { get; set; }
        public virtual DbSet<GCC_SOLICITUD_CREDITO> GCC_SOLICITUD_CREDITO { get; set; }
        public virtual DbSet<IMP_ACCION> IMP_ACCION { get; set; }
        public virtual DbSet<IMP_ACTIVIDAD> IMP_ACTIVIDAD { get; set; }
        public virtual DbSet<IMP_ACTIVIDAD_PLANIFICADA> IMP_ACTIVIDAD_PLANIFICADA { get; set; }
        public virtual DbSet<IMP_ADQUISICION> IMP_ADQUISICION { get; set; }
        public virtual DbSet<IMP_ALERTA_ACTIVIDAD> IMP_ALERTA_ACTIVIDAD { get; set; }
        public virtual DbSet<IMP_ALERTA_EVENTO> IMP_ALERTA_EVENTO { get; set; }
        public virtual DbSet<IMP_ALMACEN_ADUANAS> IMP_ALMACEN_ADUANAS { get; set; }
        public virtual DbSet<IMP_ARTICULO> IMP_ARTICULO { get; set; }
        public virtual DbSet<IMP_BITACORA_EVENTO> IMP_BITACORA_EVENTO { get; set; }
        public virtual DbSet<IMP_BL> IMP_BL { get; set; }
        public virtual DbSet<IMP_CERTIFICADO_ISO> IMP_CERTIFICADO_ISO { get; set; }
        public virtual DbSet<IMP_CERTIFICADO_MANUFACTURA> IMP_CERTIFICADO_MANUFACTURA { get; set; }
        public virtual DbSet<IMP_CONCEPTO> IMP_CONCEPTO { get; set; }
        public virtual DbSet<IMP_DAM> IMP_DAM { get; set; }
        public virtual DbSet<IMP_DEPARTAMENTO> IMP_DEPARTAMENTO { get; set; }
        public virtual DbSet<IMP_DESADUANAJE> IMP_DESADUANAJE { get; set; }
        public virtual DbSet<IMP_DETALLE_FACTURA_COMERCIAL> IMP_DETALLE_FACTURA_COMERCIAL { get; set; }
        public virtual DbSet<IMP_DETALLE_ORDEN_COMPRA> IMP_DETALLE_ORDEN_COMPRA { get; set; }
        public virtual DbSet<IMP_DISTRITO> IMP_DISTRITO { get; set; }
        public virtual DbSet<IMP_EVENTO> IMP_EVENTO { get; set; }
        public virtual DbSet<IMP_FACTURA_COMERCIAL> IMP_FACTURA_COMERCIAL { get; set; }
        public virtual DbSet<IMP_ORDEN_COMPRA> IMP_ORDEN_COMPRA { get; set; }
        public virtual DbSet<IMP_PAGO_IMPORTACION> IMP_PAGO_IMPORTACION { get; set; }
        public virtual DbSet<IMP_PROVEEDOR> IMP_PROVEEDOR { get; set; }
        public virtual DbSet<IMP_PROVINCIA> IMP_PROVINCIA { get; set; }
        public virtual DbSet<IMP_PUERTO> IMP_PUERTO { get; set; }
        public virtual DbSet<IMP_RESOLUCION_DIGEMID> IMP_RESOLUCION_DIGEMID { get; set; }
        public virtual DbSet<IMP_SOLICITUD> IMP_SOLICITUD { get; set; }
        public virtual DbSet<IMP_SOLICITUD_GESTION_PERMISO> IMP_SOLICITUD_GESTION_PERMISO { get; set; }
        public virtual DbSet<IMP_SOLICITUD_IMPORTACION> IMP_SOLICITUD_IMPORTACION { get; set; }
        public virtual DbSet<IMP_TIPO_ACTIVIDAD> IMP_TIPO_ACTIVIDAD { get; set; }
        public virtual DbSet<IMP_TIPO_CAMBIO> IMP_TIPO_CAMBIO { get; set; }
        public virtual DbSet<IMP_TIPO_EVENTO> IMP_TIPO_EVENTO { get; set; }
        public virtual DbSet<IMP_TIPO_MONEDA> IMP_TIPO_MONEDA { get; set; }
        public virtual DbSet<IMP_TIPO_PAGO> IMP_TIPO_PAGO { get; set; }
        public virtual DbSet<RRH_AlternativaAutoevaluacion> RRH_AlternativaAutoevaluacion { get; set; }
        public virtual DbSet<RRH_AlternativaEvaluacionTecnica> RRH_AlternativaEvaluacionTecnica { get; set; }
        public virtual DbSet<RRH_Area> RRH_Area { get; set; }
        public virtual DbSet<RRH_Candidato> RRH_Candidato { get; set; }
        public virtual DbSet<RRH_Criterio> RRH_Criterio { get; set; }
        public virtual DbSet<RRH_CurriculumVitae> RRH_CurriculumVitae { get; set; }
        public virtual DbSet<RRH_Empleado> RRH_Empleado { get; set; }
        public virtual DbSet<RRH_OfertaLaboral> RRH_OfertaLaboral { get; set; }
        public virtual DbSet<RRH_OfertaLaboral_Candidato> RRH_OfertaLaboral_Candidato { get; set; }
        public virtual DbSet<RRH_Perfil> RRH_Perfil { get; set; }
        public virtual DbSet<RRH_PreguntaEvaluacionTecnica> RRH_PreguntaEvaluacionTecnica { get; set; }
        public virtual DbSet<RRH_PruebaAuotoevaluacion> RRH_PruebaAuotoevaluacion { get; set; }
        public virtual DbSet<RRH_PruebaEvaluacionTecnica> RRH_PruebaEvaluacionTecnica { get; set; }
        public virtual DbSet<RRH_Puesto> RRH_Puesto { get; set; }
        public virtual DbSet<RRH_Sucursal> RRH_Sucursal { get; set; }
        public virtual DbSet<RYA_ACTARECEP_CAB> RYA_ACTARECEP_CAB { get; set; }
        public virtual DbSet<RYA_ACTARECEP_DET> RYA_ACTARECEP_DET { get; set; }
        public virtual DbSet<RYA_ALMACENES> RYA_ALMACENES { get; set; }
        public virtual DbSet<RYA_LOTES> RYA_LOTES { get; set; }
        public virtual DbSet<RYA_MOVALM_CAB> RYA_MOVALM_CAB { get; set; }
        public virtual DbSet<RYA_MOVALM_DET> RYA_MOVALM_DET { get; set; }
        public virtual DbSet<RYA_PEDIDO_CAB> RYA_PEDIDO_CAB { get; set; }
        public virtual DbSet<RYA_PEDIDO_DET> RYA_PEDIDO_DET { get; set; }
        public virtual DbSet<RYA_PRODUCTO> RYA_PRODUCTO { get; set; }
        public virtual DbSet<RYA_STOCK> RYA_STOCK { get; set; }
        public virtual DbSet<RYA_SUCURSALES> RYA_SUCURSALES { get; set; }
        public virtual DbSet<RYA_TRANSA_ALMA> RYA_TRANSA_ALMA { get; set; }
        public virtual DbSet<RYA_UBICACIONES> RYA_UBICACIONES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int sp_DetalleReceta_Buscar(string wHERE)
        {
            var wHEREParameter = wHERE != null ?
                new ObjectParameter("WHERE", wHERE) :
                new ObjectParameter("WHERE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DetalleReceta_Buscar", wHEREParameter);
        }
    
        public virtual int sp_Kardex_ObtenerUltimoMovimiento(string wHERE)
        {
            var wHEREParameter = wHERE != null ?
                new ObjectParameter("WHERE", wHERE) :
                new ObjectParameter("WHERE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Kardex_ObtenerUltimoMovimiento", wHEREParameter);
        }
    
        public virtual int sp_Orden_Anular(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Orden_Anular", codigoParameter);
        }
    
        public virtual int sp_OrdenPreparado_Actualizar(string codigo_Orden, Nullable<System.DateTime> fecha, string tecnico_Farmaceutico, string receta_Cliente, string codigo_Sucursal, string codigo_Receta, string estado)
        {
            var codigo_OrdenParameter = codigo_Orden != null ?
                new ObjectParameter("Codigo_Orden", codigo_Orden) :
                new ObjectParameter("Codigo_Orden", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var tecnico_FarmaceuticoParameter = tecnico_Farmaceutico != null ?
                new ObjectParameter("Tecnico_Farmaceutico", tecnico_Farmaceutico) :
                new ObjectParameter("Tecnico_Farmaceutico", typeof(string));
    
            var receta_ClienteParameter = receta_Cliente != null ?
                new ObjectParameter("Receta_Cliente", receta_Cliente) :
                new ObjectParameter("Receta_Cliente", typeof(string));
    
            var codigo_SucursalParameter = codigo_Sucursal != null ?
                new ObjectParameter("Codigo_Sucursal", codigo_Sucursal) :
                new ObjectParameter("Codigo_Sucursal", typeof(string));
    
            var codigo_RecetaParameter = codigo_Receta != null ?
                new ObjectParameter("Codigo_Receta", codigo_Receta) :
                new ObjectParameter("Codigo_Receta", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_OrdenPreparado_Actualizar", codigo_OrdenParameter, fechaParameter, tecnico_FarmaceuticoParameter, receta_ClienteParameter, codigo_SucursalParameter, codigo_RecetaParameter, estadoParameter);
        }
    
        public virtual int sp_OrdenPreparado_Crear(string codigo_Orden, Nullable<System.DateTime> fecha, string tecnico_Farmaceutico, string receta_Cliente, string codigo_Sucursal, string codigo_Receta, string estado)
        {
            var codigo_OrdenParameter = codigo_Orden != null ?
                new ObjectParameter("Codigo_Orden", codigo_Orden) :
                new ObjectParameter("Codigo_Orden", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var tecnico_FarmaceuticoParameter = tecnico_Farmaceutico != null ?
                new ObjectParameter("Tecnico_Farmaceutico", tecnico_Farmaceutico) :
                new ObjectParameter("Tecnico_Farmaceutico", typeof(string));
    
            var receta_ClienteParameter = receta_Cliente != null ?
                new ObjectParameter("Receta_Cliente", receta_Cliente) :
                new ObjectParameter("Receta_Cliente", typeof(string));
    
            var codigo_SucursalParameter = codigo_Sucursal != null ?
                new ObjectParameter("Codigo_Sucursal", codigo_Sucursal) :
                new ObjectParameter("Codigo_Sucursal", typeof(string));
    
            var codigo_RecetaParameter = codigo_Receta != null ?
                new ObjectParameter("Codigo_Receta", codigo_Receta) :
                new ObjectParameter("Codigo_Receta", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_OrdenPreparado_Crear", codigo_OrdenParameter, fechaParameter, tecnico_FarmaceuticoParameter, receta_ClienteParameter, codigo_SucursalParameter, codigo_RecetaParameter, estadoParameter);
        }
    
        public virtual int sp_Receta_Buscar(string wHERE)
        {
            var wHEREParameter = wHERE != null ?
                new ObjectParameter("WHERE", wHERE) :
                new ObjectParameter("WHERE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Receta_Buscar", wHEREParameter);
        }
    
        public virtual int sp_Table_List(string tabla)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("Tabla", tabla) :
                new ObjectParameter("Tabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Table_List", tablaParameter);
        }
    
        public virtual int sp_Table_List_Codigo_Orden(string filtro)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Table_List_Codigo_Orden", filtroParameter);
        }
    
        public virtual int sp_Table_List_Nom_Receta(string filtro)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Table_List_Nom_Receta", filtroParameter);
        }
    
        public virtual int sp_Table_List_Nom_Sucursal(string filtro)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Table_List_Nom_Sucursal", filtroParameter);
        }
    
        public virtual int sp_Table_List_Todos(string tabla)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("Tabla", tabla) :
                new ObjectParameter("Tabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Table_List_Todos", tablaParameter);
        }
    
        public virtual ObjectResult<usp_Chofer_GetAll_Result> usp_Chofer_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Chofer_GetAll_Result>("usp_Chofer_GetAll");
        }
    }
}
