//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chofer
    {
        public int IdChofer { get; set; }
        public string NroDoc { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NroTelefono { get; set; }
        public string NroLicencia { get; set; }
        public string CateLicencia { get; set; }
    }
}
