//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleKardex
    {
        public int NumeroKardex { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<int> TipodeMovimiento { get; set; }
        public string NumeroNotaIngreso { get; set; }
        public string NumeroSalida { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    }
}
