//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_Producto
    {
        public DIS_Producto()
        {
            this.DIS_Pedido_Detalle = new HashSet<DIS_Pedido_Detalle>();
            this.IMP_DETALLE_ORDEN_COMPRA = new HashSet<IMP_DETALLE_ORDEN_COMPRA>();
        }
    
        public int Cod_producto { get; set; }
        public string Nom_producto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cod_tipo_producto { get; set; }
        public Nullable<int> Cod_presentacion_producto { get; set; }
        public Nullable<decimal> Peso_producto { get; set; }
        public string Unidad_medida { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> cod_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_regi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ICollection<DIS_Pedido_Detalle> DIS_Pedido_Detalle { get; set; }
        public virtual DIS_PresentacionProducto DIS_PresentacionProducto { get; set; }
        public virtual ICollection<IMP_DETALLE_ORDEN_COMPRA> IMP_DETALLE_ORDEN_COMPRA { get; set; }
        public virtual DIS_TipoProducto DIS_TipoProducto { get; set; }
    }
}
