//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_Pedido
    {
        public DIS_Pedido()
        {
            this.DIS_HojaRutaDetalle = new HashSet<DIS_HojaRutaDetalle>();
            this.DIS_Pedido_Detalle = new HashSet<DIS_Pedido_Detalle>();
        }
    
        public int Cod_pedido { get; set; }
        public Nullable<System.DateTime> Fec_pedido { get; set; }
        public Nullable<int> Cod_sucursal { get; set; }
        public string Tipo_prioridad { get; set; }
        public string Observacion { get; set; }
        public Nullable<short> Estado { get; set; }
        public Nullable<int> cod_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_regi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ICollection<DIS_HojaRutaDetalle> DIS_HojaRutaDetalle { get; set; }
        public virtual RRH_Sucursal RRH_Sucursal { get; set; }
        public virtual ICollection<DIS_Pedido_Detalle> DIS_Pedido_Detalle { get; set; }
    }
}
