//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_HojaRuta
    {
        public DIS_HojaRuta()
        {
            this.DIS_HojaRutaDetalle = new HashSet<DIS_HojaRutaDetalle>();
        }
    
        public int Cod_hoja_ruta { get; set; }
        public Nullable<int> Cod_control_asignacines { get; set; }
        public Nullable<System.DateTime> Fec_creacion { get; set; }
        public Nullable<System.DateTime> Fec_despacho { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> cod_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_regi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual DIS_Control_Asignacion DIS_Control_Asignacion { get; set; }
        public virtual ICollection<DIS_HojaRutaDetalle> DIS_HojaRutaDetalle { get; set; }
    }
}
