//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_HojaRutaDetalle
    {
        public int Cod_hoja_ruta_detalle { get; set; }
        public Nullable<int> Cod_hoja_ruta { get; set; }
        public Nullable<int> Cod_pedido { get; set; }
        public Nullable<int> cod_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_regi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual DIS_HojaRuta DIS_HojaRuta { get; set; }
        public virtual DIS_Pedido DIS_Pedido { get; set; }
    }
}
