//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_Control_Asignacion
    {
        public DIS_Control_Asignacion()
        {
            this.DIS_HojaRuta = new HashSet<DIS_HojaRuta>();
        }
    
        public int Cod_control_asignacines { get; set; }
        public Nullable<int> Cod_vehiculo { get; set; }
        public Nullable<int> Cod_transportista { get; set; }
        public Nullable<System.DateTime> Fec_registro { get; set; }
        public string Turno { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> cod_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_regi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual DIS_Transportista DIS_Transportista { get; set; }
        public virtual DIS_Vehiculo DIS_Vehiculo { get; set; }
        public virtual ICollection<DIS_HojaRuta> DIS_HojaRuta { get; set; }
    }
}
