//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_Transportista
    {
        public DIS_Transportista()
        {
            this.DIS_Control_Asignacion = new HashSet<DIS_Control_Asignacion>();
        }
    
        public int Cod_transportista { get; set; }
        public Nullable<int> Cod_empleado { get; set; }
        public string Num_licencia { get; set; }
        public string Cat_licencia { get; set; }
        public Nullable<short> Estado { get; set; }
        public Nullable<int> cod_usu_regi { get; set; }
        public Nullable<int> cod_usu_modi { get; set; }
        public Nullable<System.DateTime> fec_usu_regi { get; set; }
        public Nullable<System.DateTime> fec_usu_modi { get; set; }
    
        public virtual ICollection<DIS_Control_Asignacion> DIS_Control_Asignacion { get; set; }
    }
}
