//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_COMPROBANTE
    {
        public GCC_COMPROBANTE()
        {
            this.GCC_NOTIFICACION = new HashSet<GCC_NOTIFICACION>();
        }
    
        public string Tipo_documento { get; set; }
        public string Num_documento { get; set; }
        public int Cod_cliente { get; set; }
        public System.DateTime Fec_documento { get; set; }
        public System.DateTime Fec_vencimiento { get; set; }
        public System.DateTime Fec_pago { get; set; }
        public string Moneda { get; set; }
        public decimal Importe { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual GCC_CLIENTE GCC_CLIENTE { get; set; }
        public virtual ICollection<GCC_NOTIFICACION> GCC_NOTIFICACION { get; set; }
    }
}
