//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_NOTIFICACION
    {
        public int Cod_notificacion { get; set; }
        public string Tipo_documento { get; set; }
        public string Num_documento { get; set; }
        public System.DateTime Fec_notificacion { get; set; }
        public string Tipo_notificacion { get; set; }
        public string Desccripcion { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
        public int Cod_politica { get; set; }
    
        public virtual GCC_COMPROBANTE GCC_COMPROBANTE { get; set; }
        public virtual GCC_POLITICAS_NOTIFICACION GCC_POLITICAS_NOTIFICACION { get; set; }
    }
}
