//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GCC_CLIENTE
    {
        public GCC_CLIENTE()
        {
            this.GCC_COMPROBANTE = new HashSet<GCC_COMPROBANTE>();
        }

        public int Cod_cliente { get; set; }
        public string Tipo_doc_identidad { get; set; }
        [Required(ErrorMessage = "RUC es requerido.")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Debe Ingresar valor numérico")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Debe ingresar RUC valido: XXXXXXXXXXX")]
        public string Num_doc_identidad { get; set; }
        [Required(ErrorMessage = "Dirección es requerido.")]
        [StringLength(150, MinimumLength = 1, ErrorMessage = "No puede superar 150 caracteres")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "Teléfono es requerido.")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Ingrese solo números")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Email es requerido.")]
        [RegularExpression("^([a-zA-Z0-9_\\-\\.]+)@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,3})$", ErrorMessage = "Debe ingresar correo con el formato válido xxxx@xxxx.xx")]
        //[RegularExpression("^([a-zA-Z0-9_\\-\\.]+)@[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,3})$", ErrorMessage = "Email ingresado no es válido")]
        public string Correo { get; set; }
        public string Estado { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }

        public virtual GCC_CLIENTE_JURIDICO GCC_CLIENTE_JURIDICO { get; set; }
        public virtual GCC_CLIENTE_NATURAL GCC_CLIENTE_NATURAL { get; set; }
        public virtual ICollection<GCC_COMPROBANTE> GCC_COMPROBANTE { get; set; }
        public string Estado_str
        {
            get
            {

                if (Estado == "A")
                {
                    return "Activo";
                }
                else if (Estado == "D")
                {
                    return "Inactivo";
                }

                return "";
            }
        }

    }
}
