//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_CLIENTE
    {
        public GCC_CLIENTE()
        {
            this.GCC_COMPROBANTE = new HashSet<GCC_COMPROBANTE>();
        }
    
        public int Cod_cliente { get; set; }
        public string Tipo_doc_identidad { get; set; }
        public string Num_doc_identidad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Estado { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual GCC_CLIENTE_JURIDICO GCC_CLIENTE_JURIDICO { get; set; }
        public virtual GCC_CLIENTE_NATURAL GCC_CLIENTE_NATURAL { get; set; }
        public virtual ICollection<GCC_COMPROBANTE> GCC_COMPROBANTE { get; set; }
    }
}
