//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_INFORME_CREDITICIO
    {
        public GCC_INFORME_CREDITICIO()
        {
            this.GCC_DOCUMENTO_RECHAZO = new HashSet<GCC_DOCUMENTO_RECHAZO>();
            this.GCC_EMPLEADO_INF_CREDITICIO = new HashSet<GCC_EMPLEADO_INF_CREDITICIO>();
        }
    
        public int Cod_informe_crediticio { get; set; }
        public int Cod_solicitud_credito { get; set; }
        public int Cod_politica_credito { get; set; }
        public System.DateTime Fecha_informe { get; set; }
        public string Nivel_riesgo { get; set; }
        public string Capacidad_crediticia { get; set; }
        public System.DateTime Fec_ultima_evaluacion { get; set; }
        public byte[] Reporte_infocorp { get; set; }
        public decimal Monto_linea_credito_eval { get; set; }
        public decimal Monto_linea_credito_aprob { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<GCC_DOCUMENTO_RECHAZO> GCC_DOCUMENTO_RECHAZO { get; set; }
        public virtual ICollection<GCC_EMPLEADO_INF_CREDITICIO> GCC_EMPLEADO_INF_CREDITICIO { get; set; }
        public virtual GCC_POLITICA_CREDITO GCC_POLITICA_CREDITO { get; set; }
        public virtual GCC_SOLICITUD_CREDITO GCC_SOLICITUD_CREDITO { get; set; }
    }
}
