//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_POLITICAS_NOTIFICACION
    {
        public GCC_POLITICAS_NOTIFICACION()
        {
            this.GCC_NOTIFICACION = new HashSet<GCC_NOTIFICACION>();
        }
    
        public int Cod_politica { get; set; }
        public string Num_politica { get; set; }
        public string Nombre_politica { get; set; }
        public int Dias_vencimiento { get; set; }
        public string Tipo_mensaje { get; set; }
        public string Descripcion_mensaje { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<GCC_NOTIFICACION> GCC_NOTIFICACION { get; set; }
    }
}
