//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_CUENTA_CLIENTE
    {
        public int Cod_cuenta_cliente { get; set; }
        public int Cod_contrato_credito { get; set; }
        public string Num_cuenta { get; set; }
        public decimal Linea_credito { get; set; }
        public decimal Linea_disponible { get; set; }
        public string Estado_cuenta { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual GCC_CONTRATO_CREDITO GCC_CONTRATO_CREDITO { get; set; }
    }
}
