//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_POLITICA_CREDITO
    {
        public GCC_POLITICA_CREDITO()
        {
            this.GCC_INFORME_CREDITICIO = new HashSet<GCC_INFORME_CREDITICIO>();
        }
    
        public int Cod_politica_credito { get; set; }
        public string Num_politica { get; set; }
        public string Nombre_politica { get; set; }
        public string Descripcion { get; set; }
        public string Nivel_riesgo { get; set; }
        public bool Cliente_nuevo { get; set; }
        public int Num_movimientos { get; set; }
        public int Porcentaje_pago_fecha { get; set; }
        public string Capacidad_crediticia { get; set; }
        public int Cod_plan_credito { get; set; }
        public string Estado_resultante { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<GCC_INFORME_CREDITICIO> GCC_INFORME_CREDITICIO { get; set; }
        public virtual GCC_PLAN_CREDITO GCC_PLAN_CREDITO { get; set; }
    }
}
