//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_CONTRATO_CREDITO
    {
        public GCC_CONTRATO_CREDITO()
        {
            this.GCC_CUENTA_CLIENTE = new HashSet<GCC_CUENTA_CLIENTE>();
        }
    
        public int Cod_contrato_credito { get; set; }
        public int Cod_solicitud_credito { get; set; }
        public System.DateTime Fec_inicio { get; set; }
        public System.DateTime Fec_renovacion { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual GCC_SOLICITUD_CREDITO GCC_SOLICITUD_CREDITO { get; set; }
        public virtual ICollection<GCC_CUENTA_CLIENTE> GCC_CUENTA_CLIENTE { get; set; }
    }
}
