//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GCC_INFORME_CREDITICIO
    {
        public GCC_INFORME_CREDITICIO()
        {
            this.GCC_DOCUMENTO_RECHAZO = new HashSet<GCC_DOCUMENTO_RECHAZO>();
            this.GCC_EMPLEADO_INF_CREDITICIO = new HashSet<GCC_EMPLEADO_INF_CREDITICIO>();
        }
    
        public int Cod_informe_crediticio { get; set; }
        public int Cod_solicitud_credito { get; set; }
        public int Cod_politica_credito { get; set; }
        [Display(Name = "Fecha Informe")]
        public System.DateTime Fecha_informe { get; set; }
        public string Nivel_riesgo { get; set; }
        public string Capacidad_crediticia { get; set; }
        [Display(Name = "Fecha Ultima Evaluación")]
        public System.DateTime Fec_ultima_evaluacion { get; set; }
        public Byte[] Reporte_infocorp { get; set; }
        [Display(Name = "Linea de Crédito Evaluado")]
        public decimal Monto_linea_credito_eval { get; set; }
        [Display(Name = "Linea de Crédito Aprobado")]
        public decimal Monto_linea_credito_aprob { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<GCC_DOCUMENTO_RECHAZO> GCC_DOCUMENTO_RECHAZO { get; set; }
        public virtual ICollection<GCC_EMPLEADO_INF_CREDITICIO> GCC_EMPLEADO_INF_CREDITICIO { get; set; }
        public virtual GCC_POLITICA_CREDITO GCC_POLITICA_CREDITO { get; set; }
        public virtual GCC_SOLICITUD_CREDITO GCC_SOLICITUD_CREDITO { get; set; }
        [Display(Name = "Nivel Riesgo")]
        public string Nivel_riesgo_str { get{
            if (Nivel_riesgo == "A") {
                return "Alto";
            }
            else if (Nivel_riesgo == "M")
            {
                return "Medio";
            }
            else if (Nivel_riesgo == "B")
            {
                return "Bajo";
            }

            return "";
            } 
        }
        [Display(Name = "Capacidad Crediticia")]
        public string Capacidad_crediticia_str
        {
            get
            {
                if (Capacidad_crediticia == "A")
                {
                    return "Alto";
                }
                else if (Capacidad_crediticia == "M")
                {
                    return "Medio";
                }
                else if (Capacidad_crediticia == "B")
                {
                    return "Bajo";
                }

                return "";
            }
        }
        [Display(Name = "Estado")]
        public string Estado_actual
        {
            get
            {
                
                var estados = new List<Models.GCC_EMPLEADO_INF_CREDITICIO>(GCC_EMPLEADO_INF_CREDITICIO);
                String estado_actual = estados[estados.Count - 1].Estado;

                if (estado_actual == "A")
                {
                    estado_actual = "Aprobado";
                }
                else if (estado_actual == "R")
                {
                    estado_actual = "Registrado";
                }
                else if (estado_actual == "M")
                {
                    estado_actual = "Modificado";
                }
                else if (estado_actual == "O")
                {
                    estado_actual = "Anulado";
                }
                else if (estado_actual == "Z")
                {
                    estado_actual = "Rechazado";
                }
                else if (estado_actual == "G")
                {
                    estado_actual = "Generado";
                }

                return estado_actual;
            }
        }
    }
}
