//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_SOLICITUD_GESTION_PERMISO
    {
        public IMP_SOLICITUD_GESTION_PERMISO()
        {
            this.IMP_ACTIVIDAD_PLANIFICADA = new HashSet<IMP_ACTIVIDAD_PLANIFICADA>();
            this.IMP_CERTIFICADO_ISO = new HashSet<IMP_CERTIFICADO_ISO>();
            this.IMP_CERTIFICADO_MANUFACTURA = new HashSet<IMP_CERTIFICADO_MANUFACTURA>();
            this.IMP_RESOLUCION_DIGEMID = new HashSet<IMP_RESOLUCION_DIGEMID>();
        }
    
        public int Cod_solicitud_gestion_permiso { get; set; }
        public Nullable<System.DateTime> Fec_aprobacion { get; set; }
        public Nullable<int> Cod_solicitud { get; set; }
        public int Cod_articulo { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
        public int Cod_empleado { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<IMP_ACTIVIDAD_PLANIFICADA> IMP_ACTIVIDAD_PLANIFICADA { get; set; }
        public virtual IMP_ARTICULO IMP_ARTICULO { get; set; }
        public virtual ICollection<IMP_CERTIFICADO_ISO> IMP_CERTIFICADO_ISO { get; set; }
        public virtual ICollection<IMP_CERTIFICADO_MANUFACTURA> IMP_CERTIFICADO_MANUFACTURA { get; set; }
        public virtual ICollection<IMP_RESOLUCION_DIGEMID> IMP_RESOLUCION_DIGEMID { get; set; }
        public virtual IMP_SOLICITUD IMP_SOLICITUD { get; set; }
        public virtual RRH_Empleado RRH_Empleado { get; set; }
    }
}
