//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_ARTICULO
    {
        public IMP_ARTICULO()
        {
            this.IMP_DETALLE_FACTURA_COMERCIAL = new HashSet<IMP_DETALLE_FACTURA_COMERCIAL>();
            this.IMP_SOLICITUD_GESTION_PERMISO = new HashSet<IMP_SOLICITUD_GESTION_PERMISO>();
        }
    
        public int Cod_articulo { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fec_elaboracion { get; set; }
        public Nullable<decimal> Precio_unitario { get; set; }
        public string Clasificacion { get; set; }
        public string Indicaciones { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<IMP_DETALLE_FACTURA_COMERCIAL> IMP_DETALLE_FACTURA_COMERCIAL { get; set; }
        public virtual ICollection<IMP_SOLICITUD_GESTION_PERMISO> IMP_SOLICITUD_GESTION_PERMISO { get; set; }
    }
}
