//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_DESADUANAJE
    {
        public IMP_DESADUANAJE()
        {
            this.IMP_ALERTA_EVENTO = new HashSet<IMP_ALERTA_EVENTO>();
            this.IMP_BITACORA_EVENTO = new HashSet<IMP_BITACORA_EVENTO>();
            this.IMP_DAM = new HashSet<IMP_DAM>();
        }
    
        public int Cod_desaduanaje { get; set; }
        public Nullable<int> Cod_solicitud_importacion { get; set; }
        public Nullable<System.DateTime> Fec_inicio_desaduanaje { get; set; }
        public Nullable<System.DateTime> Fec_retiro_mercaderia { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
        public Nullable<int> Cod_almacen_aduanas { get; set; }
    
        public virtual ICollection<IMP_ALERTA_EVENTO> IMP_ALERTA_EVENTO { get; set; }
        public virtual ICollection<IMP_BITACORA_EVENTO> IMP_BITACORA_EVENTO { get; set; }
        public virtual ICollection<IMP_DAM> IMP_DAM { get; set; }
        public virtual IMP_SOLICITUD_IMPORTACION IMP_SOLICITUD_IMPORTACION { get; set; }
    }
}
