//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_ORDEN_COMPRA
    {
        public IMP_ORDEN_COMPRA()
        {
            this.IMP_DETALLE_ORDEN_COMPRA = new HashSet<IMP_DETALLE_ORDEN_COMPRA>();
            this.IMP_SOLICITUD_IMPORTACION = new HashSet<IMP_SOLICITUD_IMPORTACION>();
        }
    
        public int Cod_orden_compra { get; set; }
        public Nullable<int> Num_orden_compra { get; set; }
        public Nullable<System.DateTime> Fec_orden_compra { get; set; }
        public Nullable<int> Cod_proveedor { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<IMP_DETALLE_ORDEN_COMPRA> IMP_DETALLE_ORDEN_COMPRA { get; set; }
        public virtual IMP_PROVEEDOR IMP_PROVEEDOR { get; set; }
        public virtual ICollection<IMP_SOLICITUD_IMPORTACION> IMP_SOLICITUD_IMPORTACION { get; set; }
    }
}
