//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_ALERTA
    {
        public int Cod_alerta { get; set; }
        public string Nombre_alerta { get; set; }
        public string Disparador_estado_actividad { get; set; }
        public string Disparador_fecha_cierre_planificado { get; set; }
        public string Repetir_dia { get; set; }
        public Nullable<System.DateTime> Fec_inicio { get; set; }
        public Nullable<System.DateTime> Fec_fin { get; set; }
        public Nullable<int> Cod_actividad_planificada { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual IMP_ACTIVIDAD_PLANIFICADA IMP_ACTIVIDAD_PLANIFICADA { get; set; }
    }
}
