//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_RESOLUCION_DIGEMID
    {
        public int Cod_resolucion { get; set; }
        public Nullable<int> Num_resolucion { get; set; }
        public Nullable<System.DateTime> Fec_resolucion { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string Archivo { get; set; }
        public Nullable<int> Cod_solicitud_gestio_permiso { get; set; }
        public int Cod_usu_regi { get; set; }
        public System.DateTime Fec_usu_regi { get; set; }
        public Nullable<int> Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual IMP_SOLICITUD_GESTION_PERMISO IMP_SOLICITUD_GESTION_PERMISO { get; set; }
    }
}
