//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_ALMACEN_ADUANAS
    {
        public int Cod_almacen_aduanas { get; set; }
        public string Nombre { get; set; }
        public string Razon_social { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Cod_puerto { get; set; }
    
        public virtual IMP_PUERTO IMP_PUERTO { get; set; }
    }
}
