//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int NumeroKardex { get; set; }
        public int IdProducto { get; set; }
        public int IdAlmacen { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> SaldoActual { get; set; }
    }
}
