//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaSalida
    {
        public string NumeroSalida { get; set; }
        public string NumeroPedido { get; set; }
        public string FechaSalida { get; set; }
        public Nullable<int> idAlmacen { get; set; }
        public string UsuarioPicking { get; set; }
        public string Observaciones { get; set; }
    }
}
