//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public string NumeroPedido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public string UsuarioAsignado { get; set; }
    }
}
