//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_CurriculumVitae
    {
        public RRH_CurriculumVitae()
        {
            this.RRH_Candidato = new HashSet<RRH_Candidato>();
        }
    
        public int Cod_cv_cand { get; set; }
        public string Estudios1_candidato { get; set; }
        public string Universidad1_candidato { get; set; }
        public string Estudios2_candidato { get; set; }
        public string Universidad2_candidato { get; set; }
        public string Estudios3_candidato { get; set; }
        public string Universidad3_candidato { get; set; }
        public string Expericiencialaboral1 { get; set; }
        public string Desc_experiencialaboral1 { get; set; }
        public string Expericiencialaboral2 { get; set; }
        public string Desc_experiencialaboral2 { get; set; }
        public Nullable<int> Anos_experiencialaboral { get; set; }
        public string Referencia1 { get; set; }
        public string Desc_referencia1 { get; set; }
        public string Referencia2 { get; set; }
        public string Desc_referencia2 { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<RRH_Candidato> RRH_Candidato { get; set; }
    }
}
