//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_Detalle_PruebaEvaluacionTecnica
    {
        public int Cod_detalleevaltec { get; set; }
        public Nullable<int> Cod_pruebaevaltec { get; set; }
        public Nullable<int> Cod_respevaltec { get; set; }
        public Nullable<int> Cod_alternativa_evaltec { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RRH_AlternativaEvaluacionTecnica RRH_AlternativaEvaluacionTecnica { get; set; }
        public virtual RRH_PruebaEvaluacionTecnica RRH_PruebaEvaluacionTecnica { get; set; }
        public virtual RRH_RespuestaEvaluacionTecnica RRH_RespuestaEvaluacionTecnica { get; set; }
    }
}
