//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_Criterio_PruebaAutoevaluacion
    {
        public int Cod_autoevaluacion { get; set; }
        public int Cod_criterio { get; set; }
        public Nullable<int> Cod_alternatica_autoevaluacion { get; set; }
    
        public virtual RRH_AlternativaAutoevaluacion RRH_AlternativaAutoevaluacion { get; set; }
        public virtual RRH_Criterio RRH_Criterio { get; set; }
        public virtual RRH_PruebaAutoevaluacion RRH_PruebaAutoevaluacion { get; set; }
    }
}
