//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_RespuestaEvaluacionTecnica
    {
        public RRH_RespuestaEvaluacionTecnica()
        {
            this.RRH_Detalle_PruebaEvaluacionTecnica = new HashSet<RRH_Detalle_PruebaEvaluacionTecnica>();
        }
    
        public int Cod_respevaltec { get; set; }
        public Nullable<int> Cod_alternativa_evaltec { get; set; }
        public Nullable<int> Cod_preg_evaltec { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RRH_AlternativaEvaluacionTecnica RRH_AlternativaEvaluacionTecnica { get; set; }
        public virtual ICollection<RRH_Detalle_PruebaEvaluacionTecnica> RRH_Detalle_PruebaEvaluacionTecnica { get; set; }
        public virtual RRH_PreguntaEvaluacionTecnica RRH_PreguntaEvaluacionTecnica { get; set; }
    }
}
