//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_EMPLEADO
    {
        public RRH_EMPLEADO()
        {
            this.ALP_CONSTANCIA_PREPARADO = new HashSet<ALP_CONSTANCIA_PREPARADO>();
            this.ALP_HOJA_MERMA = new HashSet<ALP_HOJA_MERMA>();
            this.ALP_LIBRO_RECETA = new HashSet<ALP_LIBRO_RECETA>();
            this.ALP_LIBRO_RECETA_PSICOTROPICO = new HashSet<ALP_LIBRO_RECETA_PSICOTROPICO>();
            this.ALP_ORDEN_PREPARADO = new HashSet<ALP_ORDEN_PREPARADO>();
            this.ALP_SOLICITUD_TRANSPORTE = new HashSet<ALP_SOLICITUD_TRANSPORTE>();
        }
    
        public int cod_empleado { get; set; }
        public string Nom_empleado { get; set; }
        public string Ap_paterno { get; set; }
        public string Ap_materno { get; set; }
        public string Dni { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> Fec_Ingreso { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
        public Nullable<int> Cod_puesto { get; set; }
    
        public virtual ICollection<ALP_CONSTANCIA_PREPARADO> ALP_CONSTANCIA_PREPARADO { get; set; }
        public virtual ICollection<ALP_HOJA_MERMA> ALP_HOJA_MERMA { get; set; }
        public virtual ICollection<ALP_LIBRO_RECETA> ALP_LIBRO_RECETA { get; set; }
        public virtual ICollection<ALP_LIBRO_RECETA_PSICOTROPICO> ALP_LIBRO_RECETA_PSICOTROPICO { get; set; }
        public virtual ICollection<ALP_ORDEN_PREPARADO> ALP_ORDEN_PREPARADO { get; set; }
        public virtual ICollection<ALP_SOLICITUD_TRANSPORTE> ALP_SOLICITUD_TRANSPORTE { get; set; }

        internal dynamic GetEmpleado()
        {
            string temp = Nom_empleado + " " + Ap_paterno + " " + Ap_materno;

            return String.IsNullOrEmpty(temp) ? "" : temp;
        }
    }
}
