//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_Usuario
    {
        public string Cod_usuario { get; set; }
        public int Cod_Empleado { get; set; }
        public string UserName { get; set; }
        public string Contrasena { get; set; }
    
        public virtual RRH_Empleado RRH_Empleado { get; set; }
    }
}
