//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_AlternativaAutoevaluacion
    {
        public RRH_AlternativaAutoevaluacion()
        {
            this.RRH_PruebaAuotoevaluacion = new HashSet<RRH_PruebaAuotoevaluacion>();
        }
    
        public int Cod_alternativa_autoevaluacion { get; set; }
        public string Respuesta { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<System.DateTime> Fec_creacion { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
        public Nullable<int> Cod_criterio { get; set; }
    
        public virtual RRH_Criterio RRH_Criterio { get; set; }
        public virtual ICollection<RRH_PruebaAuotoevaluacion> RRH_PruebaAuotoevaluacion { get; set; }
    }
}
