//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_GradoAcademico
    {
        public int Cod_GradoAcademico { get; set; }
        public int Cod_candidato { get; set; }
        public string Especialidad { get; set; }
        public string CentroEstudios { get; set; }
        public System.DateTime Fec_Graduacion { get; set; }
    
        public virtual RRH_Candidato RRH_Candidato { get; set; }
    }
}
