//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_PruebaAuotoevaluacion
    {
        public int Cod_autoevaluacion { get; set; }
        public Nullable<System.DateTime> Fec_evaluacion { get; set; }
        public string VersionEvaluacion { get; set; }
        public Nullable<int> ResultadoPreg1 { get; set; }
        public Nullable<int> ResultadoPreg2 { get; set; }
        public Nullable<int> ResultadoPreg3 { get; set; }
        public Nullable<int> ResultadoPreg4 { get; set; }
        public Nullable<int> ResultadoPreg5 { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
        public Nullable<int> Cod_empleado { get; set; }
        public Nullable<int> Cod_alternativa_autoevaluacion { get; set; }
    
        public virtual RRH_AlternativaAutoevaluacion RRH_AlternativaAutoevaluacion { get; set; }
        public virtual RRH_Empleado RRH_Empleado { get; set; }
    }
}
