//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_RespuestaAutoevaluacion
    {
        public RRH_RespuestaAutoevaluacion()
        {
            this.RRH_PruebaAutoevaluacion_Respuesta = new HashSet<RRH_PruebaAutoevaluacion_Respuesta>();
        }
    
        public int Cod_resp_autoevaluacion { get; set; }
        public int Cod_criterio { get; set; }
        public string Respuesta { get; set; }
        public int Puntaje { get; set; }
        public string Cod_usu_reg { get; set; }
        public Nullable<System.DateTime> Fec_usu_reg { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RRH_Criterio RRH_Criterio { get; set; }
        public virtual ICollection<RRH_PruebaAutoevaluacion_Respuesta> RRH_PruebaAutoevaluacion_Respuesta { get; set; }
    }
}
