//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_ReferenciaLaboral
    {
        public int Cod_ReferenciaLaboral { get; set; }
        public Nullable<int> Cod_candidato { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> TipoReferencia { get; set; }
        public string Puesto { get; set; }
    
        public virtual RRH_Candidato RRH_Candidato { get; set; }
    }
}
