//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_OfertaLaboral
    {
        public RRH_OfertaLaboral()
        {
            this.RRH_OfertaLaboral_Candidato = new HashSet<RRH_OfertaLaboral_Candidato>();
        }
    
        public int Cod_ofertalaboral { get; set; }
        public string Titulo { get; set; }
        public int IdPerfil { get; set; }
        public int IdSucursal { get; set; }
        public string FuncionesAdicionales { get; set; }
        public Nullable<int> TiempoValidez { get; set; }
        public Nullable<System.DateTime> Fec_creacion { get; set; }
        public int Estado { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<RRH_OfertaLaboral_Candidato> RRH_OfertaLaboral_Candidato { get; set; }
        public virtual RRH_Perfil RRH_Perfil { get; set; }
        public virtual RRH_Sucursal RRH_Sucursal { get; set; }
    }
}
