//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_PreguntaEvaluacionTecnica
    {
        public RRH_PreguntaEvaluacionTecnica()
        {
            this.RRH_RespuestaEvaluacionTecnica = new HashSet<RRH_RespuestaEvaluacionTecnica>();
        }
    
        public int Cod_preg_evaltec { get; set; }
        public string Pregunta { get; set; }
        public Nullable<int> Cod_evaltec { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RRH_EvaluacionTecnica RRH_EvaluacionTecnica { get; set; }
        public virtual ICollection<RRH_RespuestaEvaluacionTecnica> RRH_RespuestaEvaluacionTecnica { get; set; }
    }
}
