//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_PruebaAutoevaluacion_Respuesta
    {
        public int Cod_PruebaAutoevaluacion_Respuesta { get; set; }
        public int Cod_prueba_autoevaluacion { get; set; }
        public int Cod_resp_autoevaluacion { get; set; }
    
        public virtual RRH_PruebaAutoevaluacion RRH_PruebaAutoevaluacion { get; set; }
        public virtual RRH_RespuestaAutoevaluacion RRH_RespuestaAutoevaluacion { get; set; }
    }
}
