//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_Area
    {
        public RRH_Area()
        {
            this.RRH_Puesto = new HashSet<RRH_Puesto>();
            this.RRH_Empleado = new HashSet<RRH_Empleado>();
        }
    
        public int Cod_area { get; set; }
        public string Nombre { get; set; }
        public int Estado { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<RRH_Puesto> RRH_Puesto { get; set; }
        public virtual ICollection<RRH_Empleado> RRH_Empleado { get; set; }
    }
}
