//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_Perfil
    {
        public RRH_Perfil()
        {
            this.RRH_OfertaLaboral = new HashSet<RRH_OfertaLaboral>();
        }
    
        public int Cod_perfil { get; set; }
        public int Cod_puesto { get; set; }
        public string Nombre { get; set; }
        public string Desc_perfil { get; set; }
        public string Competencias { get; set; }
        public string Caracteristicas { get; set; }
        public Nullable<decimal> SueldoIni { get; set; }
        public Nullable<decimal> SueldoFin { get; set; }
        public int Estado { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual ICollection<RRH_OfertaLaboral> RRH_OfertaLaboral { get; set; }
        public virtual RRH_Puesto RRH_Puesto { get; set; }
    }
}
