//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRH_EvaluacionTecnica
    {
        public RRH_EvaluacionTecnica()
        {
            this.RRH_PreguntaEvaluacionTecnica = new HashSet<RRH_PreguntaEvaluacionTecnica>();
        }
    
        public int Cod_evaltec { get; set; }
        public Nullable<System.DateTime> Fec_creacion { get; set; }
        public Nullable<int> Cod_perfil { get; set; }
        public Nullable<int> Cod_criterio { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RRH_Criterio RRH_Criterio { get; set; }
        public virtual ICollection<RRH_PreguntaEvaluacionTecnica> RRH_PreguntaEvaluacionTecnica { get; set; }
        public virtual RRH_Perfil RRH_Perfil { get; set; }
    }
}
