//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RYA_LOTES
    {
        public RYA_LOTES()
        {
            this.RYA_STOCK = new HashSet<RYA_STOCK>();
            this.RYA_UBICACIONES = new HashSet<RYA_UBICACIONES>();
        }
    
        public int Cod_Lote { get; set; }
        public int COD_PRODUCTO { get; set; }
        public string Lote { get; set; }
        public System.DateTime fch_fab { get; set; }
        public System.DateTime fch_vto { get; set; }
        public System.DateTime cantidad { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RYA_PRODUCTO RYA_PRODUCTO { get; set; }
        public virtual ICollection<RYA_STOCK> RYA_STOCK { get; set; }
        public virtual ICollection<RYA_UBICACIONES> RYA_UBICACIONES { get; set; }
    }
}
