//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RYA_UBICACIONES
    {
        public int Cod_Almacen { get; set; }
        public int Cod_Lote { get; set; }
        public int COD_PRODUCTO { get; set; }
        public string Lote { get; set; }
        public int Cant { get; set; }
        public string modulo { get; set; }
        public Nullable<int> columna { get; set; }
        public Nullable<int> fila { get; set; }
        public string Cod_usu_regi { get; set; }
        public Nullable<System.DateTime> Fec_usu_regi { get; set; }
        public string Cod_usu_modi { get; set; }
        public Nullable<System.DateTime> Fec_usu_modi { get; set; }
    
        public virtual RYA_LOTES RYA_LOTES { get; set; }
    }
}
