//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RYA_MOVALM_DET
    {
        public int Cod_sucursal { get; set; }
        public int Cod_Almacen { get; set; }
        public int TipoDoc { get; set; }
        public int NumDoc { get; set; }
        public int item { get; set; }
        public int COD_PRODUCTO { get; set; }
        public string Lote { get; set; }
        public string UnidadMedida { get; set; }
        public int Cant { get; set; }
    
        public virtual RYA_MOVALM_CAB RYA_MOVALM_CAB { get; set; }
        public virtual RYA_PRODUCTO RYA_PRODUCTO { get; set; }
    }
}
