//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int idUbicacion { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public string Fila { get; set; }
        public string Columna { get; set; }
        public string Nivel { get; set; }
        public string posicion { get; set; }
    }
}
