USE [BDBoticas]
--- select * from DIS_Producto

INSERT INTO DIS_TipoProducto(Des_Tipo_Producto) VALUES('Medicinas')
INSERT INTO DIS_PresentacionProducto(Des_Presentacion_Producto) VALUES('Frascos')

INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ACEITE DE RICINO 60 ML', 'ACEITE DE RICINO 60 ML', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ACETAMINOFEN 500MG TABLETA', 'ACETAMINOFEN 500MG TABLETA',1,1, 'TAB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ACETATO DE ALUMINIO POLVO/SOB X 2,2 G', 'ACETATO DE ALUMINIO POLVO/SOB X 2,2 G', 1,1,'SOB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ACIDO FOLICO 1 MG TABLETA', 'ACIDO FOLICO 1 MG TABLETA', 1,1,'TAB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('AGUA OXIGENADA 120 ML FCO', 'AGUA OXIGENADA 120 ML FCO', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ALCOHOL AL 96% X 50 ML FCO', 'ALCOHOL AL 96% X 50 ML FCO', 1,1,'UND', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ALCOHOL AL 70% X 50 ML FCO', 'ALCOHOL AL 70% X 50 ML FCO', 1,1,'UND', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ALCOHOL ANTISEPTICO /FCO X 750 ML', 'ALCOHOL ANTISEPTICO /FCO X 750 ML', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('ALGODON EN TORUNDAS PAQUETE X 300', 'ALGODON EN TORUNDAS PAQUETE X 300', 1,1,'BOL', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('AMPICILINA 1GR  AMP', 'AMPICILINA 1GR  AMP', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('AMPICILINA 500 MG CAPSULA', 'AMPICILINA 500 MG CAPSULA', 1,1,'TAB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('GUANTE DESECHABLE N.7.0 ESTERIL', 'GUANTE DESECHABLE N.7.0 ESTERIL', 1,1,'SOB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('GUANTE DESECHABLE N.7.5 ESTERIL', 'GUANTE DESECHABLE N.7.5 ESTERIL', 1,1,'SOB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('GUANTE NO ESTERIL SMOLL X 100 UN', 'GUANTE NO ESTERIL SMOLL X 100 UN', 1,1,'CAJA', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('GUANTE NO ESTERIL SMOLL X 100 UN', 'GUANTE NO ESTERIL SMOLL X 100 UN', 1,1,'CAJA', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('GUANTES DESECHABLE N-8.5 ESTERIL', 'GUANTES DESECHABLE N-8.5 ESTERIL', 1,1,'SOB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('LECHE MAGNESIA  X 360 ML',	'LECHE MAGNESIA  X 360 ML', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('LECHE NAN HA1X400GR', 'LECHE NAN HA1X400GR', 1,1,'TAR', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('LECHE NAN SIN LACTOSA X 400 GR', 'LECHE NAN SIN LACTOSA X 400 GR', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('NUTREN POLVO 400 MG', 'NUTREN POLVO 400 MG', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('NUTREN POLVO DIABETES 400GR', 'NUTREN POLVO DIABETES 400GR', 1,1,'FCO', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('RANITIDINA 150 MG  TABLETA', 'RANITIDINA 150 MG  TABLETA',1,1, 'TAB', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('RANITIDINA 50 MG/2 ML AMP', 'RANITIDINA 50 MG/2 ML AMP', 1,1,'AMP', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('SONDA FOLEY N 8', 'SONDA FOLEY N 8', 1,1,'UND', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('SONDA FOLEY N-10', 'SONDA FOLEY N-10',1,1, 'UND', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('SONDA FOLEY N-14', 'SONDA FOLEY N-14',1,1, 'UND', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('TERMOMETRO ORAL', 'TERMOMETRO ORAL', 1,1,'UND', 1)
INSERT INTO [BDBoticas].[dbo].[DIS_Producto]([Nom_producto],[Descripcion],[Cod_Tipo_Producto], [Cod_presentacion_Producto],[unidad_medida],[Estado]) values ('TERRAMICINA UNGUENTO OFTALMICO  X  10 G', 'TERRAMICINA UNGUENTO OFTALMICO  X  10 G', 1,1,'TUB', 1)


INSERT INTO [BDBoticas].[dbo].[RRH_Sucursal]([Nom_sucursal],[Direccion]) VALUES ('Sucursal Breña','Av. Venezuela 1232')
INSERT INTO [BDBoticas].[dbo].[RRH_Sucursal]([Nom_sucursal],[Direccion]) VALUES ('Sucursal Lince','Av. Risso 2542')
INSERT INTO [BDBoticas].[dbo].[RRH_Sucursal]([Nom_sucursal],[Direccion]) VALUES ('Sucursal Los Olivos','Av. Las Palmeras 545')
INSERT INTO [BDBoticas].[dbo].[RRH_Sucursal]([Nom_sucursal],[Direccion]) VALUES ('Sucursal Chosica','Av. El Sol 874')
INSERT INTO [BDBoticas].[dbo].[RRH_Sucursal]([Nom_sucursal],[Direccion]) VALUES ('Sucursal Jesus Maria','Av. Pachacutec 782')

INSERT INTO RRH_Area(Nombre, Estado) VALUES('Salud', 1)

INSERT INTO [BDBoticas].[dbo].[RRH_Puesto]([Nom_puesto],[Cod_Area],[Estado]) VALUES ('Gerente General', 1,1)
INSERT INTO [BDBoticas].[dbo].[RRH_Puesto]([Nom_puesto],[Cod_Area],[Estado]) VALUES ('Jefe de Almacen', 1,1)
INSERT INTO [BDBoticas].[dbo].[RRH_Puesto]([Nom_puesto],[Cod_Area],[Estado]) VALUES ('Asistente Administrador Almacen', 1,1)
INSERT INTO [BDBoticas].[dbo].[RRH_Puesto]([Nom_puesto],[Cod_Area],[Estado]) VALUES ('Auxiliar de Almacen', 1,1)

INSERT INTO [BDBoticas].[dbo].[RRH_Empleado]([Nom_empleado],[Ap_paterno],[Ap_materno],[Cod_puesto],[Fec_Ingreso]) VALUES ('Juan','Perez','Mattos',1,GETDATE()-500)
INSERT INTO [BDBoticas].[dbo].[RRH_Empleado]([Nom_empleado],[Ap_paterno],[Ap_materno],[Cod_puesto],[Fec_Ingreso]) VALUES ('Juan','Abascal','Gamboa',2,GETDATE()-500)
INSERT INTO [BDBoticas].[dbo].[RRH_Empleado]([Nom_empleado],[Ap_paterno],[Ap_materno],[Cod_puesto],[Fec_Ingreso]) VALUES ('Joel','Rodriguez','Miranda',3,GETDATE()-500)
INSERT INTO [BDBoticas].[dbo].[RRH_Empleado]([Nom_empleado],[Ap_paterno],[Ap_materno],[Cod_puesto],[Fec_Ingreso]) VALUES ('Manuel','Marreros','Ayllon',3,GETDATE()-500)
INSERT INTO [BDBoticas].[dbo].[RRH_Empleado]([Nom_empleado],[Ap_paterno],[Ap_materno],[Cod_puesto],[Fec_Ingreso]) VALUES ('Jose','Carbajal','Palomino',2,GETDATE()-500)
INSERT INTO [BDBoticas].[dbo].[RRH_Empleado]([Nom_empleado],[Ap_paterno],[Ap_materno],[Cod_puesto],[Fec_Ingreso]) VALUES ('Irene','Martinez','Ciprian',4,GETDATE()-500)

INSERT INTO [BDBoticas].[dbo].[RYA_ALMACENES]([Descripcion],[Cod_sucursal]) VALUES ('Almacen General',1)
INSERT INTO [BDBoticas].[dbo].[RYA_ALMACENES]([Descripcion],[Cod_sucursal]) VALUES ('Medicinas refrigeradas',1)
INSERT INTO [BDBoticas].[dbo].[RYA_ALMACENES]([Descripcion],[Cod_sucursal]) VALUES ('Materia Prima',2)
INSERT INTO [BDBoticas].[dbo].[RYA_ALMACENES]([Descripcion],[Cod_sucursal]) VALUES ('Almacen Liquidos',2)

INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (2,'201280',getdate()-360,getdate()+520,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (2,'201280',getdate()-360,getdate()+520,3250)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (23,'212520',getdate()-521,getdate()+320,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (3,'444051',getdate()-254,getdate()+260,3500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (3,'254203',getdate()-360,getdate()+250,600)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (4,'215460',getdate()-360,getdate()+580,1250)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (5,'110150',getdate()-545,getdate()+420,854)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (6,'254312',getdate()-124,getdate()+120,520)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (7,'558004',getdate()-214,getdate()+520,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (7,'505010',getdate()-312,getdate()+320,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (8,'558010',getdate()-212,getdate()+410,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (8,'887015',getdate()-245,getdate()+240,12500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (9,'120258',getdate()-245,getdate()+300,21500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (10,'120389',getdate()-541,getdate()+360,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (11,'985420',getdate()-235,getdate()+320,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (11,'205456',getdate()-210,getdate()+220,21500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (11,'201260',getdate()-260,getdate()+210,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (10,'585403',getdate()-312,getdate()+320,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (14,'854012',getdate()-304,getdate()+270,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (17,'220122',getdate()-122,getdate()+280,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (20,'545501',getdate()-451,getdate()+520,2500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (21,'221554',getdate()-210,getdate()+220,1)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (22,'854584',getdate()-260,getdate()+210,2)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (24,'324552',getdate()-312,getdate()+320,10)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (26,'985548',getdate()-304,getdate()+270,3)
INSERT INTO [BDBoticas].[dbo].[RYA_LOTES]([COD_PRODUCTO],[Lote],[fch_fab],[fch_vto],[cantidad]) VALUES (28,'100256',getdate()-122,getdate()+280,1)

INSERT INTO [BDBoticas].[dbo].[RYA_STOCK] ([Cod_sucursal],[Cod_Almacen],[COD_PRODUCTO],[Cod_Lote],[Cant])
select 1, 1, cod_producto, cod_lote, cantidad from rya_lotes

---------------------------------
INSERT INTO RYA_PEDIDO_CAB(NumPedido, FchPedido, FchEntrega, Estado, Cod_Sucursal, CodSolicitante) VALUES('OP000001', GETDATE(), GETDATE()+10, '1', 1, 1)
INSERT INTO RYA_PEDIDO_CAB(NumPedido, FchPedido, FchEntrega, Estado, Cod_Sucursal, CodSolicitante) VALUES('OP000002', GETDATE(), GETDATE()+10, '1', 1, 1)
INSERT INTO RYA_PEDIDO_CAB(NumPedido, FchPedido, FchEntrega, Estado, Cod_Sucursal, CodSolicitante) VALUES('OP000003', GETDATE(), GETDATE()+10, '1', 1, 1)

INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(1, 1, 2, 2, 0, 'FCO')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(2, 1, 1, 1, 0, 'TAB')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(3, 1, 3, 3, 0, 'SOB')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(9, 2, 5, 5, 0, 'BOL')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(11, 2, 20, 20, 0, 'TAB')						
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(12, 2, 15, 15, 0, 'SOB')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(19, 3, 14, 14, 0, 'FCO')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(20, 3, 5, 5, 0, 'FCO')
INSERT INTO RYA_PEDIDO_DET(Cod_producto, NumPedido, Cant, Cant_Aprob, Cant_Atendida, UnidadMedida) VALUES(26, 3, 6, 6, 0, 'UND')


INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (1,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (2,'A',100,300)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (3,'A',20,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (4,'A',200,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (5,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (6,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (7,'A',220,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (8,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (9,'A',300,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (10,'A',520,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (11,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (12,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (13,'A',200,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (14,'A',300,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (15,'A',300,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (16,'A',210,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (17,'A',50,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (18,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (19,'A',100,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (20,'A',100,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (21,'A',200,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (22,'A',200,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (23,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (24,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (25,'A',110,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (26,'A',130,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (27,'A',120,500)
INSERT INTO [BDBoticas].[dbo].[RYA_LOGISTICO]([cod_producto],[clasificacion],[stock_min],[stock_max]) VALUES (28,'A',120,500)



